# SPDX-FileCopyrightText: 2021 City of Turku
#
# SPDX-License-Identifier: LGPL-2.1-or-later

# used with the evakaturku-local profile, overlaying eVaka's local profile properties
# profile priority defined by "last wins" -strategy of spring.profiles.active declarations (build file/env var)
---
debug: true

spring:
  devtools:
    livereload:
      enabled: false
  main:
    logStartupInfo: false
logging:
  level:
    fi:
      espoo:
        evaka: DEBUG
        evaka.invoicing.integration.IntegrationClient: DEBUG
      turku:
        evakaturku: DEBUG
    org:
      springframework:
        boot:
          autoconfigure: INFO

evaka:
  aws:
    region: eu-west-1
  five_years_old_daycare:
    enabled: false
  integration:
    koski:
      enabled: false

evakaturku:
  sapInvoicing:
    username: user
    password: pass
    address: address
    path: path
  sapPayments:
    username: user
    password: pass
    address: address
    path: path
