# SPDX-FileCopyrightText: 2021 City of Turku
#
# SPDX-License-Identifier: LGPL-2.1-or-later

spring:
  application:
    name: "evakaturku-service"

evaka:
  email:
    sender_address: "no-reply.evaka@turku.fi"
    sender_name:
      fi: "Turun Varhaiskasvatus"
      sv: "Åbo småbarnspedagogik"
    application_received:
      sender_address:
        fi: "vaka.palveluohjaus@turku.fi"
        sv: "dagis@turku.fi"
      sender_name:
        fi: "Varhaiskasvatuksen palveluohjaus"
        sv: "Barninvalskoordinatorer / Turku stad"
  oph:
    organizer_oid: "1.2.246.562.10.79499343246"
    organizer_id: "176"
    municipality_code: "813"
