# SPDX-FileCopyrightText: 2021 City of Turku
#
# SPDX-License-Identifier: LGPL-2.1-or-later

spring:
  application:
    name: "evakaturku-service"

evaka:
  email:
    sender_address: "no-reply.evaka@turku.fi"
    sender_name:
      fi: "Turun varhaiskasvatus"
      sv: "Åbo småbarnsperdagogik"
    application_received:
      sender_address:
        fi: "varhaiskasvatus.palveluohjaus@turku.fi"
        sv: "varhaiskasvatus.palveluohjaus@turku.fi"
      sender_name:
        fi: "Varhaiskasvatuksen palveluohjaus"
        sv: "Service enheten vid småbarnspedagogik"
  oph:
    organizer_oid: "1.2.246.562.10.56820737825"
    organizer_id: "PUUTTUU"
    municipality_code: "853"